# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-04-23 22:55:58

context("File R/add_labels.R: @testexamples")

test_that("Function add_labels() @ L51", {
  
  # Load mutational signature
  load(system.file("extdata", "toy_mutational_signature.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Show signature profile
  p <- show_sig_profile(sig2, mode = "SBS")
  
  # Method 1
  p1 <- add_labels(p,
    x = 0.75, y = 0.3, y_end = 0.9, n_label = 3,
    labels = paste0("text", 1:3)
  )
  p1
  
  # Method 2
  p2 <- add_labels(p,
    x = c(0.15, 0.6, 0.75), y = c(0.3, 0.6, 0.9),
    labels = paste0("text", 1:3)
  )
  p2
  
  # Method 3
  sim <- get_sig_similarity(sig2)
  p3 <- add_labels(p,
    x = c(0.15, 0.6, 0.75), y = c(0.3, 0.6, 0.9),
    labels = sim, font_size = 2
  )
  p3
  expect_s3_class(p, "ggplot")
  expect_s3_class(p1, "ggplot")
  expect_s3_class(p2, "ggplot")
  expect_s3_class(p3, "ggplot")
})

