# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-23 13:18:56

context("File R/show_catalogue.R: @testexamples")

test_that("Function show_catalogue() @ L28", {
  
  load(system.file("extdata", "toy_copynumber_tally_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  p <- show_catalogue(cn_tally_M,
    mode = "copynumber", method = "M",
    style = "cosmic", paint_axis_text = FALSE
  )
  p
  expect_s3_class(p, "ggplot")
})

