# Generated by roxytest: do not edit by hand!

# File R/sig_fit_bootstrap_batch.R: @testexamples

test_that("Function sig_fit_bootstrap_batch() @ L63", {
  
  # For mutational signatures ----------------
  # SBS is used for illustration, similar
  # operations can be applied to DBS, INDEL, CN, RS, etc.
  
  # Load simulated data
  data("simulated_catalogs")
  data = simulated_catalogs$set1
  data[1:5, 1:5]
  
  # Fitting with COSMIC reference signatures
  
  # Generally set n = 100
  rv = sig_fit_bootstrap_batch(data,
    sig_index = c(1, 5, 9, 2, 13),
     sig_db = "SBS", n = 10)
  rv
  
  
  # For general purpose --------------------
  W <- matrix(c(1, 2, 3, 4, 5, 6), ncol = 2)
  colnames(W) <- c("sig1", "sig2")
  W <- apply(W, 2, function(x) x / sum(x))
  
  H <- matrix(c(2, 5, 3, 6, 1, 9, 1, 2), ncol = 4)
  colnames(H) <- paste0("samp", 1:4)
  
  V <- W %*% H
  V
  
  if (requireNamespace("quadprog")) {
    z10 <- sig_fit_bootstrap_batch(V, sig = W, n = 10)
    z10
  }
  expect_is(z10, "list")
  z2 <- sig_fit_bootstrap_batch(V, sig = W, n = 2, use_parallel = TRUE)
  expect_is(z2, "list")
})

