# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-13 23:05:00

context("File R/get_genome_annotation.R: @testexamples")

test_that("Function get_genome_annotation() @ L17", {
  
  df1 <- get_genome_annotation()
  df1
  
  df2 <- get_genome_annotation(genome_build = "hg38")
  df2
  expect_equal(nrow(df1), nrow(df2))
})

