# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-05-10 09:23:46

context("File R/get_sig_similarity.R: @testexamples")

test_that("Function get_sig_similarity() @ L58", {
  
  # Load mutational signature
  load(system.file("extdata", "toy_mutational_signature.RData",
    package = "sigminer", mustWork = TRUE
  ))
  
  s1 <- get_sig_similarity(sig2, Ref = sig2)
  s1
  
  s2 <- get_sig_similarity(sig2)
  s2
  s3 <- get_sig_similarity(sig2, sig_db = "SBS")
  s3
  
  ## Remove some components
  ## in similarity calculation
  s4 <- get_sig_similarity(sig2,
    Ref = sig2,
    pattern_to_rm = c("T[T>G]C", "T[T>G]G", "T[T>G]T")
  )
  s4
  
  ## Same to DBS and ID signatures
  expect_equal(length(s1), 3L)
  expect_equal(length(s2), 3L)
  expect_equal(length(s3), 3L)
  expect_equal(length(s4), 3L)
})

