# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-04-23 20:05:53

context("File R/show_sig_profile.R: @testexamples")

test_that("Function show_sig_profile() @ L115", {
  
  # Load SBS signature
  load(system.file("extdata", "toy_mutational_signature.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Show signature profile
  p1 <- show_sig_profile(sig2, mode = "SBS")
  p1
  
  # Load copy number signature from method "W"
  load(system.file("extdata", "toy_copynumber_signature_by_W.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Show signature profile
  p2 <- show_sig_profile(sig,
    style = "cosmic",
    mode = "copynumber",
    method = "W",
    normalize = "feature"
  )
  p2
  
  # Load copy number signature from method "M"
  load(system.file("extdata", "toy_copynumber_signature_by_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Show signature profile
  # The 'column' normalization is consistent with
  # original paper
  p3 <- show_sig_profile(sig,
    paint_axis_text = FALSE,
    mode = "copynumber",
    method = "M", normalize = "column"
  )
  p3
  
  # Add params label
  # =================
  # Load copy number prepare object
  load(system.file("extdata", "toy_copynumber_tally_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  params <- get_tidy_parameter(cn_tally_M$components)
  p4 <- show_sig_profile(sig,
    mode = "copynumber",
    method = "M", normalize = "column",
    params = params, y_expand = 2
  )
  p4
  expect_s3_class(p1, "ggplot")
  expect_s3_class(p2, "ggplot")
  expect_s3_class(p3, "ggplot")
  expect_s3_class(p4, "ggplot")
})

