# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-05-10 20:32:12

context("File R/sig_fit_bootstrap_batch.R: @testexamples")

test_that("Function sig_fit_bootstrap_batch() @ L34", {
  
  W <- matrix(c(1, 2, 3, 4, 5, 6), ncol = 2)
  colnames(W) <- c("sig1", "sig2")
  W <- apply(W, 2, function(x) x / sum(x))
  
  H <- matrix(c(2, 5, 3, 6, 1, 9, 1, 2), ncol = 4)
  colnames(H) <- paste0("samp", 1:4)
  
  V <- W %*% H
  V
  
  if (requireNamespace("lsei") & requireNamespace("quadprog")) {
    z <- sig_fit_bootstrap_batch(V, sig = W, n = 10)
    z
  }
  expect_is(z, "list")
})

