# Generated by roxytest: Do not edit by hand!

# File R/get_sig_db.R: @testexamples

test_that("Function get_sig_db() @ L59", {
  
  s1 <- get_sig_db()
  s2 <- get_sig_db("SBS")
  s3 <- get_sig_db("DBS")
  s4 <- get_sig_db("DBS_mm10")
  s5 <- get_sig_db("SBS_Nik_lab")
  s6 <- get_sig_db("ID")
  s7 <- get_sig_db("RS_BRCA560")
  s8 <- get_sig_db("RS_USARC")
  s9 <- get_sig_db("RS_Nik_lab")
  s10 <- get_sig_db("CNS_USARC")
  s11 <- get_sig_db("CNS_TCGA")
  s1
  s2
  s3
  s4
  s5
  s6
  s7
  s8
  s9
  s10
  s11
  expect_is(s1, "list")
  expect_is(s2, "list")
  expect_is(s3, "list")
  expect_is(s4, "list")
  expect_is(s5, "list")
  expect_is(s6, "list")
  expect_is(s7, "list")
  expect_is(s8, "list")
  expect_is(s9, "list")
  expect_is(s10, "list")
  expect_is(s11, "list")
})

