# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-30 11:46:30

context("File R/signature_obj_operation.R: @testexamples")

test_that("Function sig_names() @ L21", {
  
  ## Operate signature names
  load(system.file("extdata", "toy_mutational_signature.RData",
    package = "sigminer", mustWork = TRUE
  ))
  sig_names(sig2)
  cc <- sig_modify_names(sig2, new_names = c("Sig2", "Sig1", "Sig3"))
  sig_names(cc)
  
  # The older names are stored in tags.
  print(attr(cc, "tag"))
  
})


test_that("Function sig_number() @ L49", {
  
  ## Get signature number
  sig_number(sig2)
  
})


test_that("Function sig_attrs() @ L61", {
  
  ## Get signature attributes
  sig_number(sig2)
  
})


test_that("Function sig_signature() @ L76", {
  
  ## Get signature matrix
  z <- sig_signature(sig2)
  z <- sig_signature(sig2, normalize = "raw")
  
})


test_that("Function sig_exposure() @ L138", {
  
  ## Get exposure matrix
  ## Of note, this is different from get_sig_exposure()
  ## it returns a matrix instead of data table.
  z <- sig_exposure(sig2) # it is same as sig$Exposure
  z <- sig_exposure(sig2, type = "relative") # it is same as sig2$Exposure.norm
  
})

