# Generated by roxytest: Do not edit by hand!

context("File R/simulation.R: @testexamples")

test_that("[unknown alias] @ L53", {

  # Generate a catalog
  set.seed(1234)
  catalog <- as.integer(table(sample(1:96, 1000, replace = TRUE)))
  names(catalog) <- paste0("comp", 1:96)
  # Generate a signature
  sig <- catalog / sum(catalog)

  # Simulate catalogs
  x1 <- simulate_catalogue(catalog, 10) # 10 mutations
  x1
  x2 <- simulate_catalogue(catalog, 100) # 100 mutations
  x2
  x3 <- simulate_catalogue(catalog, 1000) # 1000 mutations
  x3
  # Similar with a signature
  x4 <- simulate_catalogue(sig, 10) # 10 mutations
  x4

  # Load SBS signature
  load(system.file("extdata", "toy_mutational_signature.RData",
    package = "sigminer", mustWork = TRUE
  ))
  s <- t(sig2$Signature.norm)
  # Generate a signature from multiple signatures/catalogs
  s1 <- simulate_signature(s)
  s1
  s2 <- simulate_signature(s, weights = 1:3)
  s2
  # Generate a catalog from multiple signatures/catalogs
  c1 <- simulate_catalogue(s, 100, weights = 1:3)
  c1
  expect_is(x1, "integer")
  expect_is(x2, "integer")
  expect_is(x3, "integer")
  expect_is(x4, "integer")
  expect_is(s1, "numeric")
  expect_is(s2, "numeric")
  expect_is(c1, "integer")
})
