# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-20 17:23:17

context("File R/optimize_sig_exposure.R: @testexamples")

test_that("Function optimize_sig_exposure() @ L41", {
  W <- matrix(c(1, 2, 3, 4, 5, 6), ncol = 2)
  colnames(W) <- c("sig1", "sig2")
  W <- apply(W, 2, function(x) x / sum(x))

  H <- matrix(c(2, 5, 3, 6, 1, 9, 1, 2), ncol = 4)
  colnames(H) <- paste0("samp", 1:4)

  V <- W %*% H
  V

  H_infer <- optimize_sig_exposure(V, W)
  H_infer
  H

  H_dt <- optimize_sig_exposure(V, W, return_class = "data.table")
  H_dt
  expect_is(H_infer, "matrix")
  expect_is(H_dt, "data.table")
})
