# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-30 11:46:30

context("File R/show_cn_circos.R: @tests")

test_that("Function show_cn_circos() @ L44", {
  load(system.file("extdata", "toy_copynumber.RData",
    package = "sigminer", mustWork = TRUE
  ))
  show_cn_circos(cn, samples = 1)
  show_cn_circos(cn, samples = "TCGA-99-7458-01A-11D-2035-01")
})

