# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-16 17:19:42

context("File R/read_copynumber.R: @testexamples")

test_that("Function read_copynumber() @ L53", {

  # Load toy dataset of absolute copynumber profile
  load(system.file("extdata", "toy_segTab.RData",
    package = "sigminer", mustWork = TRUE
  ))
  cn <- read_copynumber(segTabs,
    seg_cols = c("chromosome", "start", "end", "segVal"),
    genome_build = "hg19", complement = FALSE, verbose = TRUE
  )
  cn

  tab_file <- system.file("extdata", "metastatic_tumor.segtab.txt",
    package = "sigminer", mustWork = TRUE
  )
  cn2 <- read_copynumber(tab_file)
  cn2
  expect_s4_class(cn, "CopyNumber")
  expect_s4_class(cn2, "CopyNumber")
})
