# Generated by roxytest: Do not edit by hand!

context("File R/get_Aneuploidy_score.R: @testexamples")

test_that("Function get_Aneuploidy_score() @ L45", {
  
  # Load copy number object
  load(system.file("extdata", "toy_copynumber.RData",
    package = "sigminer", mustWork = TRUE
  ))
  
  df <- get_Aneuploidy_score(cn)
  df
  
  df2 <- get_Aneuploidy_score(cn@data)
  df2
  
  df3 <- get_Aneuploidy_score(cn@data,
    ploidy_df = get_cn_ploidy(cn@data)
  )
  df3
  expect_equal(nrow(df), 10L)
  expect_equal(nrow(df2), 10L)
  expect_equal(nrow(df3), 10L)
})

