# Generated by roxytest: Do not edit by hand!

context("File R/show_cn_features.R: @testexamples")

test_that("Function show_cn_features() @ L28", {

  # Load copy number prepare object
  load(system.file("extdata", "toy_copynumber_tally_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  p <- show_cn_features(cn_tally_M$features)
  p
  expect_s3_class(p, "ggplot")
})
