# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-05-09 21:38:37

context("File R/sig_fit.R: @testexamples")

test_that("Function sig_fit() @ L81", {
  
  W <- matrix(c(1, 2, 3, 4, 5, 6), ncol = 2)
  colnames(W) <- c("sig1", "sig2")
  W <- apply(W, 2, function(x) x / sum(x))
  
  H <- matrix(c(2, 5, 3, 6, 1, 9, 1, 2), ncol = 4)
  colnames(H) <- paste0("samp", 1:4)
  
  V <- W %*% H
  V
  
  if (requireNamespace("lsei", quietly = TRUE)) {
    H_infer <- sig_fit(V, W)
    H_infer
    H
  
    H_dt <- sig_fit(V, W, return_class = "data.table")
    H_dt
  }
  
  if (requireNamespace("quadprog", quietly = TRUE)) {
    H_infer <- sig_fit(V, W, method = "QP")
    H_infer
    H
  
    H_dt <- sig_fit(V, W, method = "QP", return_class = "data.table")
    H_dt
  }
  
  if (requireNamespace("GenSA", quietly = TRUE)) {
    H_infer <- sig_fit(V, W, method = "SA")
    H_infer
    H
  
    H_dt <- sig_fit(V, W, method = "SA", return_class = "data.table")
    H_dt
  
    ## Modify arguments to method
    sig_fit(V, W, method = "SA", maxit = 10, temperature = 100)
  }
  expect_is(H_infer, "matrix")
  expect_is(H_dt, "data.table")
})

