# Generated by roxytest: Do not edit by hand!

# File R/sig_unify_extract.R: @testexamples

test_that("Function sig_unify_extract() @ L30", {
  
  
  load(system.file("extdata", "toy_copynumber_tally_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Extract copy number signatures
  # It is same as sig_extract(cn_tally_M$nmf_matrix, 2, nrun = 1)
  res <- sig_unify_extract(cn_tally_M$nmf_matrix, 2, nrun = 1)
  
  expect_s3_class(res, "Signature")
})

