# Generated by roxytest: Do not edit by hand!

context("File R/show_sig_profile_loop.R: @testexamples")

test_that("Function show_sig_profile_loop() @ L24", {
  
  
  load(system.file("extdata", "toy_mutational_signature.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Show signature profile
  p1 <- show_sig_profile_loop(sig2, mode = "SBS")
  p1
  p2 <- show_sig_profile_loop(sig2, mode = "SBS", style = "cosmic", sig_names = c("A", "B", "C"))
  p2
  expect_s3_class(p1, "ggplot")
  expect_s3_class(p2, "ggplot")
})

