# Generated by roxytest: Do not edit by hand!

context("File R/get_sv.R: @testexamples")

test_that("Function read_sv_as_rs() @ L30", {
  
  sv <- readRDS(system.file("extdata", "toy_sv.rds", package = "sigminer", mustWork = TRUE))
  rs <- read_sv_as_rs(sv)
  
  tally_rs <- sig_tally(rs)
  
  expect_is(rs, "RS")
  expect_is(tally_rs, "list")
})

