# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-04-23 22:55:58

context("File R/sig_tally.R: @tests")

test_that("Function sig_tally() @ L87", {
  ## Load copy number object
  load(system.file("extdata", "toy_copynumber.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Use method designed by Macintyre et al.
  cn_tally_M <- sig_tally(cn, method = "M")
  # Use method designed by Wang, Shixiang et al.
  cn_tally_W <- sig_tally(cn, method = "W")
  
  expect_equal(length(cn_tally_M), length(cn_tally_W))
  
  ## for SBS
  
  laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
  laml <- read_maf(maf = laml.maf)
  if (require("BSgenome.Hsapiens.UCSC.hg19")) {
    mt_tally <- sig_tally(
      laml,
      ref_genome = "BSgenome.Hsapiens.UCSC.hg19",
      use_syn = TRUE
    )
  
    expect_equal(length(mt_tally), 3L)
  
    ## Use strand bias categories
    mt_tally <- sig_tally(
      laml,
      ref_genome = "BSgenome.Hsapiens.UCSC.hg19",
      use_syn = TRUE, add_trans_bias = TRUE
    )
    ## Test it by enrichment analysis
    dt1 = enrich_component_strand_bias(mt_tally$nmf_matrix)
    dt2 = enrich_component_strand_bias(mt_tally$all_matrice$SBS_24)
  
    expect_s3_class(dt1, "data.table")
    expect_s3_class(dt2, "data.table")
  } else {
    message("Please install package 'BSgenome.Hsapiens.UCSC.hg19' firstly!")
  }
})

