# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-04-20 16:05:21

context("File R/get_tidy_parameter.R: @testexamples")

test_that("Function get_tidy_parameter() @ L26", {
  
  load(system.file("extdata", "toy_copynumber_tally_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Get all parameters
  d1 <- get_tidy_parameter(cn_tally_M$components)
  d1
  # Get parameters for segsize feature
  d2 <- get_tidy_parameter(cn_tally_M$components$segsize)
  d2
  expect_equal(nrow(d1), 20L)
  expect_equal(nrow(d2), 10L)
})

