# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-05-11 09:50:10

context("File R/hello.R: @testexamples")

test_that("Function hello() @ L7", {
  
  hello()
  expect_message(hello(), "sigminer")
})

