# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-30 13:45:28

context("File R/get_sig_exposure.R: @testexamples")

test_that("Function get_sig_exposure() @ L28", {
  
  # Load mutational signature
  load(system.file("extdata", "toy_mutational_signature.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Get signature exposure
  expo1 <- get_sig_exposure(sig2)
  expo1
  expo2 <- get_sig_exposure(sig2, type = "relative")
  expo2
  expect_equal(nrow(expo1), 188L)
  expect_equal(nrow(expo2), 186L)
})

