# Generated by roxytest: Do not edit by hand!

# File R/cosine.R: @testexamples

test_that("Function cosine() @ L19", {
  
  x <- c(1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0)
  y <- c(0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0)
  z1 <- cosine(x, y)
  z1
  z2 <- cosine(matrix(x), matrix(y))
  z2
  expect_equal(typeof(z1), typeof(1.0))
  expect_equal(typeof(z1), typeof(matrix(1.0)))
})

