# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-13 16:22:49

context("File R/scoring.R: @testexamples")

test_that("Function scoring() @ L60", {
  
  # Load copy number object
  load(system.file("extdata", "toy_copynumber.RData",
    package = "sigminer", mustWork = TRUE
  ))
  
  d <- scoring(cn)
  d
  expect_s3_class(d, "data.frame")
})

