# Generated by roxytest: Do not edit by hand!

context("File R/transform_seg_table.R: @testexamples")

test_that("Function transform_seg_table() @ L23", {
  
  load(system.file("extdata", "toy_copynumber.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Compute the mean segVal in each cytoband
  x <- transform_seg_table(cn, resolution_factor = 1)
  x
  # Compute the mean segVal in each half-cytoband
  x2 <- transform_seg_table(cn, resolution_factor = 2)
  x2
  expect_is(x, "data.table")
  expect_is(x2, "data.table")
})

