# Generated by roxytest: do not edit by hand!

# File R/sig_extract.R: @testexamples

test_that("Function sig_extract() @ L30", {
  
  
  load(system.file("extdata", "toy_copynumber_tally_W.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Extract copy number signatures
  res <- sig_extract(cn_tally_W$nmf_matrix, 2, nrun = 1)
  
  expect_s3_class(res, "Signature")
})

