# Generated by roxytest: Do not edit by hand!

context("File R/get_shannon_diversity_index.R: @testexamples")

test_that("Function get_shannon_diversity_index() @ L34", {
  
  # Load mutational signature
  load(system.file("extdata", "toy_mutational_signature.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Get signature exposure
  rel_expo <- get_sig_exposure(sig2, type = "relative")
  rel_expo
  diversity_index <- get_shannon_diversity_index(rel_expo)
  diversity_index
  expect_is(rel_expo, "data.frame")
  expect_is(diversity_index, "data.frame")
})

