# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-19 22:27:13

context("File R/show_cosmic_signatures.R: @testexamples")

test_that("Function show_cosmic_sig_profile() @ L21", {
  show_cosmic_sig_profile()
  show_cosmic_sig_profile(sig_db = "SBS")
  show_cosmic_sig_profile(sig_index = 1:5)
  show_cosmic_sig_profile(sig_db = "SBS", sig_index = c("10a", "17a"))

  gg <- show_cosmic_sig_profile(sig_index = 1:5)
  gg$aetiology
  expect_s3_class(gg, "ggplot")
})
