# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-13 16:22:49

context("File R/show_sig_number_survey.R: @tests")

test_that("Function show_sig_number_survey() @ L97", {
  load(system.file("extdata", "toy_copynumber_tally_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  library(NMF)
  cn_estimate <- sig_estimate(cn_tally_M$nmf_matrix,
    cores = 1, nrun = 5,
    verbose = TRUE
  )
  expect_equal(length(cn_estimate), 2)
  
  # Show two measures
  p = show_sig_number_survey(cn_estimate)
  expect_s3_class(p, "ggplot")
  
  # Show one measure
  p = show_sig_number_survey(cn_estimate, right_y = NULL)
  expect_s3_class(p, "ggplot")
  p = add_h_arrow(p, x = 4.1, y = 0.953, label = "selected number")
  expect_s3_class(p, "ggplot")
  
  # Show data from a data.frame
  p = show_sig_number_survey(cn_estimate$survey)
  expect_s3_class(p, "ggplot")
  
  # Show other measures
  head(cn_estimate$survey)
  p = show_sig_number_survey(cn_estimate$survey,
    right_y = "dispersion",
    right_name = "dispersion"
  )
  expect_s3_class(p, "ggplot")
  p = show_sig_number_survey(cn_estimate$survey,
    right_y = "evar",
    right_name = "evar"
  )
  expect_s3_class(p, "ggplot")
})

