# Generated by roxytest: Do not edit by hand!

context("File R/group_enrichment.R: @testexamples")

test_that("Function group_enrichment() @ L61", {
  
  set.seed(1234)
  df <- data.frame(
    g1 = factor(abs(round(rnorm(99, 0, 1)))),
    g2 = rep(LETTERS[1:4], c(50, 40, 8, 1)),
    e1 = sample(c("P", "N"), 99, replace = TRUE),
    e2 = rnorm(99)
  )
  
  # Compare g1:e1, g1:e2, g2:e1 and g2:e2
  x1 <- group_enrichment(df, grp_vars = c("g1", "g2"), enrich_vars = c("e1", "e2"))
  x1
  
  # Only compare g1:e1, g2:e2
  x2 <- group_enrichment(df, grp_vars = c("g1", "g2"),
                         enrich_vars = c("e1", "e2"),
                         co_method = "wilcox.test",
                         cross = FALSE)
  x2
  expect_is(x1, "data.frame")
  expect_is(x2, "data.frame")
})

