# Generated by roxytest: do not edit by hand!

# File R/get_pLOH_score.R: @testexamples

test_that("Function get_pLOH_score() @ L39", {
  
  
  # Load toy dataset of absolute copynumber profile
  load(system.file("extdata", "toy_segTab.RData",
    package = "sigminer", mustWork = TRUE
  ))
  
  set.seed(1234)
  segTabs$minor_cn <- sample(c(0, 1), size = nrow(segTabs), replace = TRUE)
  cn <- read_copynumber(segTabs,
    seg_cols = c("chromosome", "start", "end", "segVal"),
    genome_measure = "wg", complement = TRUE, add_loh = TRUE
  )
  
  df <- get_pLOH_score(cn)
  df
  
  df2 <- get_pLOH_score(cn@data)
  df2
  
  expect_equal(nrow(df), 10L)
  expect_equal(nrow(df2), 10L)
})

