# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-13 23:05:00

context("File R/show_cn_profile.R: @testexamples")

test_that("Function show_cn_profile() @ L33", {
  
  # Load copy number object
  load(system.file("extdata", "toy_copynumber.RData",
    package = "sigminer", mustWork = TRUE
  ))
  
  p <- show_cn_profile(cn, nrow = 2, ncol = 1)
  p
  expect_s3_class(p, "ggplot")
})

