# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-22 18:00:31

context("File R/show_sig_exposure.R: @testexamples")

test_that("Function show_sig_exposure() @ L43", {

  # Load mutational signature
  load(system.file("extdata", "toy_mutational_signature.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Show signature exposure
  p1 <- show_sig_exposure(sig2)
  p1

  # Load copy number signature
  load(system.file("extdata", "toy_copynumber_signature_by_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Show signature exposure
  p2 <- show_sig_exposure(sig)
  p2
  expect_s3_class(p1, "ggplot")
  expect_s3_class(p2, "ggplot")
})
