# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-26 23:18:23

context("File R/show_group_comparison.R: @testexamples")

test_that("Function show_group_comparison() @ L72", {
  load(system.file("extdata", "toy_copynumber_signature_by_M.RData",
    package = "sigminer", mustWork = TRUE
  ))

  # Assign samples to clusters
  groups <- get_groups(sig, method = "k-means")

  set.seed(1234)

  groups$prob <- rnorm(10)
  groups$new_group <- sample(c("1", "2", "3", "4", NA), size = nrow(groups), replace = TRUE)

  # Compare groups (filter NAs for categorical coloumns)
  groups.cmp <- get_group_comparison(groups[, -1],
    col_group = "group",
    cols_to_compare = c("prob", "new_group"),
    type = c("co", "ca"), verbose = TRUE
  )

  # Compare groups (Set NAs of categorical columns to 'Rest')
  groups.cmp2 <- get_group_comparison(groups[, -1],
    col_group = "group",
    cols_to_compare = c("prob", "new_group"),
    type = c("co", "ca"), NAs = "Rest", verbose = TRUE
  )

  show_group_comparison(groups.cmp)

  ggcomp <- show_group_comparison(groups.cmp2)
  ggcomp$co_comb
  ggcomp$ca_comb
  expect_equal(length(groups.cmp) + 1L, length(groups.cmp) + 1)
  expect_s3_class(ggcomp$ca$new_group, "ggplot")
})
