# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-04-22 15:27:04

context("File R/show_group_mapping.R: @testexamples")

test_that("Function show_group_mapping() @ L40", {
  
  data <- dplyr::tibble(
    Group1 = rep(LETTERS[1:5], each = 10),
    Group2 = rep(LETTERS[6:15], each = 5),
    zzzz = c(rep("xx", 20), rep("yy", 20), rep(NA, 10))
  )
  p1 <- show_group_mapping(data, col_to_flow = "Group1", cols_to_map = colnames(data)[-1])
  p1
  
  p2 <- show_group_mapping(data,
    col_to_flow = "Group1", cols_to_map = colnames(data)[-1],
    include_sig = TRUE
  )
  p2
  if (!is.null(p1)) {
  expect_s3_class(p1, "ggplot")
  }
  if (!is.null(p2)) {
  expect_s3_class(p2, "ggplot")
  }
})

