# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-19 18:28:07

context("File R/sig_extract.R: @tests")

test_that("Function sig_extract() @ L39", {
  load(system.file("extdata", "toy_copynumber_tally_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Extract copy number signatures
  library(NMF)
  res <- sig_extract(cn_tally_M$nmf_matrix, 2, nrun = 1)

  expect_s3_class(res, "Signature")
})
