# Generated by roxytest: Do not edit by hand!

# File R/read_vcf.R: @testexamples

test_that("Function read_vcf() @ L23", {
  
  vcfs <- list.files(system.file("extdata", package = "sigminer"), "*.vcf", full.names = TRUE)
  
  maf <- read_vcf(vcfs)
  maf <- read_vcf(vcfs, keep_only_pass = TRUE)
  
  expect_is(maf, "MAF")
})


test_that("Function read_xena_variants() @ L155", {
  
  
  if (requireNamespace("UCSCXenaTools")) {
    library(UCSCXenaTools)
    options(use_hiplot = TRUE)
    example_file <- XenaGenerate(subset = XenaDatasets == "mc3/ACC_mc3.txt") %>%
      XenaQuery() %>%
      XenaDownload()
    x <- read_xena_variants(example_file$destfiles)
    x@data
    y <- sig_tally(x)
    y
  }
  
  if (requireNamespace("UCSCXenaTools")) {
    expect_is(y, "list")
  }
})

