# Generated by roxytest: do not edit by hand!

# File R/show_sig_profile_heatmap.R: @testexamples

test_that("Function show_sig_profile_heatmap() @ L46", {
  
  
  # Load SBS signature
  load(system.file("extdata", "toy_mutational_signature.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Show signature profile
  p1 <- show_sig_profile_heatmap(sig2, mode = "SBS")
  p1
  
  expect_s3_class(p1, "ggplot")
})

