# Generated by roxytest: Do not edit by hand!

context("File R/read_copynumber.R: @testexamples")

test_that("Function read_copynumber() @ L78", {
  
  # Load toy dataset of absolute copynumber profile
  load(system.file("extdata", "toy_segTab.RData",
    package = "sigminer", mustWork = TRUE
  ))
  cn <- read_copynumber(segTabs,
    seg_cols = c("chromosome", "start", "end", "segVal"),
    genome_build = "hg19", complement = FALSE
  )
  cn
  cn_subset <- subset(cn, sample == "TCGA-DF-A2KN-01A-11D-A17U-01")
  
  # Add LOH
  set.seed(1234)
  segTabs$minor_cn <- sample(c(0, 1), size = nrow(segTabs), replace = TRUE)
  cn <- read_copynumber(segTabs,
    seg_cols = c("chromosome", "start", "end", "segVal"),
    genome_measure = "wg", complement = TRUE, add_loh = TRUE
  )
  # Use tally method "S" (Steele et al.)
  tally_s <- sig_tally(cn, method = "S")
  
  tab_file <- system.file("extdata", "metastatic_tumor.segtab.txt",
    package = "sigminer", mustWork = TRUE
  )
  cn2 <- read_copynumber(tab_file)
  cn2
  expect_s4_class(cn, "CopyNumber")
  expect_s4_class(cn_subset, "CopyNumber")
  expect_s4_class(cn2, "CopyNumber")
  expect_is(tally_s, "list")
})

