# Generated by roxytest: Do not edit by hand!

context("File R/get_intersect_size.R: @testexamples")

test_that("Function get_intersect_size() @ L23", {
  
  o1 <- get_intersect_size(1, 5, 3, 20)
  o1
  o2 <- get_intersect_size(3, 20, 1, 10)
  o2
  o3 <- get_intersect_size(c(1, 2, 1), c(10, 4, 6), c(4, 2, 5), c(10, 3, 22))
  o3
  
  expect_equal(o1, 3)
  expect_equal(o2, 8)
  expect_equal(o3, c(7, 2, 2))
})

