# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-05-10 20:32:12

context("File R/get_genome_annotation.R: @testexamples")

test_that("Function get_genome_annotation() @ L36", {
  
  df1 <- get_genome_annotation()
  df1
  
  df2 <- get_genome_annotation(genome_build = "hg38")
  df2
  
  df3 <- get_genome_annotation(data_type = "centro_loc")
  df3
  
  df4 <- get_genome_annotation(data_type = "centro_loc", genome_build = "hg38")
  df4
  
  df5 <- get_genome_annotation(data_type = "cytobands")
  df5
  
  df6 <- get_genome_annotation(data_type = "cytobands", genome_build = "hg38")
  df6
  expect_equal(nrow(df1), nrow(df2))
  expect_equal(nrow(df3), nrow(df4))
  expect_equal(nrow(df5), nrow(df6))
  
  expect_equal(identical(df1, df2), FALSE)
  expect_equal(identical(df3, df4), FALSE)
  expect_equal(identical(df5, df6), FALSE)
})

