# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-17 22:38:17

context("File R/read_maf.R: @testexamples")

test_that("Function read_maf() @ L20", {
  
  laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools", mustWork = TRUE)
  laml <- read_maf(maf = laml.maf)
  laml
  expect_s4_class(laml, "MAF")
})

