# Generated by roxytest: Do not edit by hand!

context("File R/show_group_distribution.R: @testexamples")

test_that("Function show_group_distribution() @ L26", {
  
  set.seed(1234)
  data <- data.frame(
    y = rnorm(120),
    g = c(rep("A", 50), rep("B", 40), rep("C", 30))
  )
  p <- show_group_distribution(data, gvar = 2, dvar = 1, background_color = "grey")
  p
  expect_is(p, "ggplot")
})

