# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-04-28 21:14:18

context("File R/show_cn_distribution.R: @testexamples")

test_that("Function show_cn_distribution() @ L32", {
  
  # Load copy number object
  load(system.file("extdata", "toy_copynumber.RData",
    package = "sigminer", mustWork = TRUE
  ))
  # Plot distribution
  p1 <- show_cn_distribution(cn)
  p1
  p2 <- show_cn_distribution(cn, mode = "cd")
  p2
  p3 <- show_cn_distribution(cn, mode = "cd", fill = TRUE)
  p3
  expect_s3_class(p1, "ggplot")
  expect_s3_class(p2, "ggplot")
  expect_s3_class(p3, "ggplot")
})

