# Generated by roxytest: Do not edit by hand!

context("File R/read_vcf.R: @testexamples")

test_that("Function read_xena_variants() @ L126", {
  
  if (requireNamespace("UCSCXenaTools")) {
    library(UCSCXenaTools)
    options(use_hiplot = TRUE)
    example_file <- XenaGenerate(subset = XenaDatasets == "mc3/ACC_mc3.txt") %>%
      XenaQuery() %>%
      XenaDownload()
    x <- read_xena_variants(example_file$destfiles)
    x@data
    y <- sig_tally(x)
    y
  }
  if (requireNamespace("UCSCXenaTools")) {
    expect_is(y, "list")
  }
})

