# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-04-17 18:16:06

context("File R/sig_auto_extract.R: @testexamples")

test_that("Function sig_auto_extract() @ L74", {
  
  load(system.file("extdata", "toy_copynumber_tally_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  res <- sig_auto_extract(cn_tally_M$nmf_matrix, result_prefix = "Test_copynumber", nrun = 1)
  # At default, all run files are stored in tempdir()
  dir(tempdir(), pattern = "Test_copynumber")
  expect_s3_class(res, "Signature")
  res <- sig_auto_extract(cn_tally_M$nmf_matrix, result_prefix = "test",
                          method = "L1KL", nrun = 1)
  expect_s3_class(res, "Signature")
  res <- sig_auto_extract(cn_tally_M$nmf_matrix, result_prefix = "test",
                          method = "L2KL", nrun = 1)
  expect_s3_class(res, "Signature")
})

