# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-04-17 15:35:27

context("File R/hello.R: @testexamples")

test_that("Function hello() @ L7", {
  
  hello()
  expect_message(hello(), "sigminer")
})

