# Generated by roxytest: Do not edit by hand!

context("File R/show_catalogue.R: @testexamples")

test_that("Function show_catalogue() @ L23", {
  
  data("simulated_catalogs")
  p <- show_catalogue(simulated_catalogs$set1, style = "cosmic")
  p
  expect_s3_class(p, "ggplot")
})

