# Generated by roxytest: do not edit by hand!

# File R/show_catalogue.R: @testexamples

test_that("Function show_catalogue() @ L23", {
  
  data("simulated_catalogs")
  p <- show_catalogue(simulated_catalogs$set1, style = "cosmic")
  if (interactive()) p
  expect_s3_class(p, "ggplot")
})

