# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-04-23 22:33:48

context("File R/sig_fit_bootstrap.R: @testexamples")

test_that("Function sig_fit_bootstrap() @ L41", {
  
  W <- matrix(c(1, 2, 3, 4, 5, 6), ncol = 2)
  colnames(W) <- c("sig1", "sig2")
  W <- apply(W, 2, function(x) x / sum(x))
  
  H <- matrix(c(2, 5, 3, 6, 1, 9, 1, 2), ncol = 4)
  colnames(H) <- paste0("samp", 1:4)
  
  V <- W %*% H
  V
  
  if (requireNamespace("lsei", quietly = TRUE)) {
    H_bootstrap <- sig_fit_bootstrap(V[, 1], W, n = 100, type = "absolute")
    ## Typically, you have to run many times to get close to the answer
    boxplot(t(H_bootstrap$expo))
    H[, 1]
  }
  expect_is(H_bootstrap, "list")
})

