# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-05-05 18:37:11

context("File R/show_cn_components.R: @testexamples")

test_that("Function show_cn_components() @ L37", {
  
  load(system.file("extdata", "toy_copynumber_tally_M.RData",
    package = "sigminer", mustWork = TRUE
  ))
  p1 <- show_cn_components(cn_tally_M$parameters)
  p1
  p2 <- show_cn_components(cn_tally_M$parameters, show_weights = FALSE)
  p2
  
  load(system.file("extdata", "toy_copynumber_tally_W.RData",
    package = "sigminer", mustWork = TRUE
  ))
  p3 <- show_cn_components(cn_tally_W$parameters, method = "W")
  p3
  expect_s3_class(p1, "ggplot")
  expect_s3_class(p2, "ggplot")
  expect_s3_class(p3, "ggplot")
})

