// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cosineVector
double cosineVector(NumericVector x, NumericVector y);
RcppExport SEXP _sigminer_cosineVector(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cosineVector(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cosineMatrix
NumericMatrix cosineMatrix(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _sigminer_cosineMatrix(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cosineMatrix(x, y));
    return rcpp_result_gen;
END_RCPP
}
// IntersectSize
NumericVector IntersectSize(NumericVector x_start, NumericVector x_end, NumericVector y_start, NumericVector y_end);
RcppExport SEXP _sigminer_IntersectSize(SEXP x_startSEXP, SEXP x_endSEXP, SEXP y_startSEXP, SEXP y_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_start(x_startSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_end(x_endSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_start(y_startSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_end(y_endSEXP);
    rcpp_result_gen = Rcpp::wrap(IntersectSize(x_start, x_end, y_start, y_end));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sigminer_cosineVector", (DL_FUNC) &_sigminer_cosineVector, 2},
    {"_sigminer_cosineMatrix", (DL_FUNC) &_sigminer_cosineMatrix, 2},
    {"_sigminer_IntersectSize", (DL_FUNC) &_sigminer_IntersectSize, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_sigminer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
