# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosineVector <- function(x, y) {
    .Call(`_sigminer_cosineVector`, x, y)
}

cosineMatrix <- function(x, y) {
    .Call(`_sigminer_cosineMatrix`, x, y)
}

pairScoreVector <- function(x, y, x_max, y_max) {
    .Call(`_sigminer_pairScoreVector`, x, y, x_max, y_max)
}

pairScoreMatrix <- function(x, y, x_max, y_max) {
    .Call(`_sigminer_pairScoreMatrix`, x, y, x_max, y_max)
}

getMatchScoreMatirx <- function(f, x, sub) {
    .Call(`_sigminer_getMatchScoreMatirx`, f, x, sub)
}

