# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosineVector <- function(x, y) {
    .Call(`_sigminer_cosineVector`, x, y)
}

cosineMatrix <- function(x, y) {
    .Call(`_sigminer_cosineMatrix`, x, y)
}

IntersectSize <- function(x_start, x_end, y_start, y_end) {
    .Call(`_sigminer_IntersectSize`, x_start, x_end, y_start, y_end)
}

