#' Show Simplified Signature Number Survey
#'
#' [sig_estimate] shows comprehensive rank survey generated by
#' **NMF** package, sometimes
#' it is hard to consider all measures. Here provides a
#' two-y-axis visualization method to help users determine
#' the optimal signature number by showing both
#' stability ("cophenetic") and error (RSS) at default.
#' Users can also set custom measures to show.
#'
#' @param object a `Survey` object generated from [sig_estimate], or
#' a `data.frame` contains at least rank columns and columns for
#' two measures.
#' @param x column name for x axis.
#' @param left_y column name for left y axis.
#' @param right_y column name for right y axis.
#' @param left_name label name for left y axis.
#' @param right_name label name for right y axis.
#' @param left_color color for left axis.
#' @param right_color color for right axis.
#'
#' @return a `ggplot` object
#' @export
#'
#' @examples
#' \donttest{
#' # Load copy number prepare object
#' load(system.file("extdata", "toy_copynumber_prepare.RData",
#'   package = "sigminer", mustWork = TRUE
#' ))
#' library(NMF)
#' cn_estimate <- sig_estimate(cn_prepare$nmf_matrix,
#'   cores = 1, nrun = 5,
#'   verbose = TRUE
#' )
#' show_sig_number_survey(cn_estimate)
#'
#' # Show data from a data.frame
#' show_sig_number_survey(cn_estimate$survey)
#' # Show other measures
#' head(cn_estimate$survey)
#' show_sig_number_survey(cn_estimate$survey,
#'   right_y = "dispersion",
#'   right_name = "dispersion"
#' )
#' show_sig_number_survey(cn_estimate$survey,
#'   right_y = "evar",
#'   right_name = "evar"
#' )
#' }
#' @seealso [sig_estimate] for estimating signature number for [sig_extract],
#' [show_sig_number_survey2] for more visualization method.
show_sig_number_survey <- function(object, x = "rank",
                                   left_y = "cophenetic", right_y = "rss",
                                   left_name = left_y, right_name = toupper(right_y),
                                   left_color = "black", right_color = "red") {
  stopifnot(class(object) == "Survey" | is.data.frame(object))
  if (class(object) == "Survey") {
    survey <- object$survey
  } else {
    survey <- object
  }

  survey$new_right <- norm2rg(
    survey[[right_y]],
    range(survey[[left_y]])
  )

  ggplot(data = survey) +
    geom_point(aes_string(x = x, y = left_y), color = left_color) +
    geom_point(aes_string(x = x, y = "new_right"), color = right_color) +
    geom_line(aes_string(x = x, y = left_y), color = left_color) +
    geom_line(aes_string(x = x, y = "new_right"), color = right_color) +
    scale_x_continuous(breaks = unique(survey[[x]]), labels = unique(survey[[x]])) +
    scale_y_continuous(
      name = left_name,
      sec.axis = sec_axis(~ norm2rg(., range(survey[[right_y]])),
        name = right_name
      )
    ) +
    cowplot::theme_cowplot() +
    xlab("Number of signature") +
    theme(
      axis.title.y.left = element_text(color = left_color),
      axis.text.y.left = element_text(color = left_color),
      axis.title.y.right = element_text(color = right_color),
      axis.text.y.right = element_text(color = right_color),
      panel.border = element_rect(colour = "black", fill = NA, size = 1)
    )
}


# Normalize data to specified range
norm2rg <- function(x, rg) {
  stopifnot(length(rg) == 2)
  k <- diff(rg) / diff(range(x))
  rg[1] + k * (x - min(x))
}
